#!/usr/bin/bash

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#ffffff80'
TEXT='#eeeeeeee'
WRONG='#00ff00bb'
VERIFYING='#ffffff'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$VERIFYING         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 8                \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%A, %Y-%m-%d"       \
--keylayout 1                \
